// <auto-generated />
using BlazorApp1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220605101015_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorApp1.Shared.Driver", b =>
                {
                    b.Property<int>("driverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("driverId"), 1L, 1);

                    b.Property<string>("driverFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driverLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("license")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("driverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            driverId = 1,
                            driverFirstName = "Dominik",
                            driverLastName = "Lugmair",
                            license = "B"
                        },
                        new
                        {
                            driverId = 2,
                            driverFirstName = "Max",
                            driverLastName = "Sieber",
                            license = "B"
                        },
                        new
                        {
                            driverId = 3,
                            driverFirstName = "Karla",
                            driverLastName = "Fuchs",
                            license = "BCD"
                        },
                        new
                        {
                            driverId = 4,
                            driverFirstName = "Marlene",
                            driverLastName = "Feuchtinger",
                            license = "BF"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Vehicle", b =>
                {
                    b.Property<int>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleId"), 1L, 1);

                    b.Property<string>("licensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requiredDL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("seats")
                        .HasColumnType("int");

                    b.HasKey("vehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            vehicleId = 1,
                            licensePlate = "L-290ND",
                            manufacturer = "Renault",
                            model = "Megane",
                            requiredDL = "B",
                            seats = 5
                        },
                        new
                        {
                            vehicleId = 2,
                            licensePlate = "L-123AB",
                            manufacturer = "VW",
                            model = "T6",
                            requiredDL = "B",
                            seats = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
