// <auto-generated />
using BlazorApp1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220606080952_testmig")]
    partial class testmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorApp1.Shared.Driver", b =>
                {
                    b.Property<int>("driverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("driverId"), 1L, 1);

                    b.Property<string>("driverFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driverLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("license")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("driverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            driverId = 1,
                            driverFirstName = "Dominik",
                            driverLastName = "Lugmair",
                            license = "B"
                        },
                        new
                        {
                            driverId = 2,
                            driverFirstName = "Max",
                            driverLastName = "Sieber",
                            license = "B"
                        },
                        new
                        {
                            driverId = 3,
                            driverFirstName = "Karla",
                            driverLastName = "Fuchs",
                            license = "BCD"
                        },
                        new
                        {
                            driverId = 4,
                            driverFirstName = "Marlene",
                            driverLastName = "Feuchtinger",
                            license = "BF"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Location", b =>
                {
                    b.Property<int>("locationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("locationId"), 1L, 1);

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("houseNr")
                        .HasColumnType("int");

                    b.Property<string>("locationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("postalCode")
                        .HasColumnType("int");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("locationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            locationId = 1,
                            country = "AUT",
                            houseNr = 82,
                            locationName = "Linz",
                            postalCode = 4030,
                            street = "Prechtlerstrasse"
                        },
                        new
                        {
                            locationId = 2,
                            country = "AUT",
                            houseNr = 69,
                            locationName = "Linz",
                            postalCode = 4040,
                            street = "Altenbergerstrasse"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Trip", b =>
                {
                    b.Property<int>("tripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tripId"), 1L, 1);

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("driverId")
                        .HasColumnType("int");

                    b.Property<double>("duration")
                        .HasColumnType("float");

                    b.Property<int>("endId")
                        .HasColumnType("int");

                    b.Property<int>("endLlocationId")
                        .HasColumnType("int");

                    b.Property<bool>("finished")
                        .HasColumnType("bit");

                    b.Property<int>("startId")
                        .HasColumnType("int");

                    b.Property<int>("startLlocationId")
                        .HasColumnType("int");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int");

                    b.HasKey("tripId");

                    b.HasIndex("driverId");

                    b.HasIndex("endLlocationId");

                    b.HasIndex("startLlocationId");

                    b.HasIndex("vehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Vehicle", b =>
                {
                    b.Property<int>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleId"), 1L, 1);

                    b.Property<string>("licensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requiredDL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("seats")
                        .HasColumnType("int");

                    b.HasKey("vehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            vehicleId = 1,
                            licensePlate = "L-290ND",
                            manufacturer = "Renault",
                            model = "Megane",
                            requiredDL = "B",
                            seats = 5
                        },
                        new
                        {
                            vehicleId = 2,
                            licensePlate = "L-123AB",
                            manufacturer = "VW",
                            model = "T6",
                            requiredDL = "B",
                            seats = 8
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Trip", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Driver", "driver")
                        .WithMany()
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Shared.Location", "endL")
                        .WithMany()
                        .HasForeignKey("endLlocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Shared.Location", "startL")
                        .WithMany()
                        .HasForeignKey("startLlocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Shared.Vehicle", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("driver");

                    b.Navigation("endL");

                    b.Navigation("startL");

                    b.Navigation("vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
